services:
  web:
    container_name: habitladder_web
    image: ${DOCKER_HUB_USERNAME}/habitladder:${DOCKER_HUB_TAG}
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    environment:
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - DB_HOST=db
      - DB_PASSWORD=${DB_PASSWORD}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - ALLOWED_HOSTS=${BASE_SERVER_URL}
    volumes:
      - hl_static_volume:/app/staticfiles
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - hl_static_volume:/app/staticfiles:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
  db:
    container_name: habitladder_db
    image: postgres:16.0
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - hl_postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
  redis:
    image: redis:alpine
    volumes:
      - hl_redis_data:/data
  celery:
    image: ${DOCKER_HUB_USERNAME}/habitladder:${DOCKER_HUB_TAG}
    command: celery -A config worker -l INFO -P solo
    env_file:
      - .env
    environment:
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - DB_PASSWORD=${DB_PASSWORD}
      - ALLOWED_HOSTS=${BASE_SERVER_URL}
    depends_on:
      - redis
      - db
  celery-beat:
    image: ${DOCKER_HUB_USERNAME}/habitladder:${DOCKER_HUB_TAG}
    command: celery -A config beat --loglevel=info
    env_file:
      - .env
    environment:
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - DB_PASSWORD=${DB_PASSWORD}
      - ALLOWED_HOSTS=${BASE_SERVER_URL}
    depends_on:
      - redis
      - db
volumes:
  hl_postgres_data:
  hl_redis_data:
  hl_static_volume:
